version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - popoffcrm_db:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: PopoffCrm.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=db;Database=PopoffCrm;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      JWT__Key: ${JWT_KEY}
    depends_on:
      - db
    ports:
      - "5000:8080"

volumes:
  popoffcrm_db:
